import time
import os
import shutil
import numpy as np
import sys
import h5py
from .mathutils import r_to_xyz

from .structure import Structure, load_structure
from .lcaodata import LCAOData
from .hrdata import read_hrr, read_vloc_shared, construct_Hloc
from .deephio import save_structure_deeph, save_mat_deeph, save_phiVdphi_deeph, save_pos_deeph
from .deephio import save_Hloc_shard, merge_Hloc_shard, assemble_ham
from .utils import mpi_watch, simple_timer, is_master, comm
from .twocenter import calc_overlap, calc_position
from .orbutils import OrbPair, PosOrbPair, prepare_position_bra
from .matlcao import MatLCAO, PairsInfo, pwc, get_mats_kb
from .gridintg import GridPoints


class PW2AOkernel:
    
    @mpi_watch
    @simple_timer('IO done, total wall time = {t}')
    def __init__(self, 
                 lcao_interface=None, lcaodata_root=None,
                 wfn_interface=None, wfndata_root=None, wfn_max_band=None, 
                 hgdata_interface=None, hrdata_interface=None,
                 vscdir=None, vkbdir=None, vasp_workdir=None, gpawsave=None, gpaw_datadir=None, upfdir=None,
                 structure_interface=None, structure_path=None,
                 overlaps_only=False,
                 gw_root=None, eqp_option='eqp1',
                 kgrid=None, ecutwfn=None):
        '''
        Parameters:
        ---------

        lcao_interface:       Currently supports 'siesta' and 'gpaw'. LCAO data is the information for atomic orbital basis.
        lcaodata_root:        If lcao_interface='siesta', then this should be folder containing x.ion where x is the atomic symbol.
                              If lcao_interface='gpaw', then this should contain x.(...).basis, where x is the atomic symbol, and 
                              the contents in the bracket is optional.
        
        hrdata_interface:     Currently supports 'qe-bgw', 'vasp', 'gpaw'. HrData is the information for the Hamiltonian in real space.
                              ecutwfn will be needed.

            If hrdata_interface='qe-bgw':   you should specify vscdir and upfdir, where upfdir is the folder containing the QE
                                         pseudopotential file x.upf.
            If hrdata_interface='vasp':  you should specify vasp_workdir containing POSCAR, POTCAR, LOCPOT and VNLOC.
            If hrdata_interface='gpaw':  you should specify gpawsave which is the binary xxx.gpw file generated by a gpaw run, and 
                                         gpaw_datadir which contains the GPAW pseudopotential x.PBE(.gz) where x is the atomic symbol, 
                                         and .gz is optional.
            If hrdata_interface='qe-deephr: you should specify vscdir (Vtot.h5) and upfdir, where upfdir is the folder containing the QE
                                         pseudopotential file x.upf. You should also provide structure information separately.

        overlaps_only:        If this is True, only the overlap will be calculated but not the Hamiltonian. The user must also provide 
                              hrdata_interface and corresponding data. 

            If hrdata_interface='qe-bgw':   only upfdir is needed, where upfdir is the folder containing the QE
                                         pseudopotential file x.upf.
            If hrdata_interface='qe-deephr': same as 'qe-bgw'.
            If hrdata_interface='vasp':  you should specify vasp_workdir, but only POTCAR is needed.
            If hrdata_interface='gpaw':  Only gpaw_datadir is needed, which contains the GPAW pseudopotential x.PBE(.gz) where 
                                         x is the atomic symbol, and .gz is optional.
        
        structure_interface:  Usually, the structure information can be automatically determined if hgdata or hrdata is provided. However,
                              if neither of these are provided, or using overlaps_only, then you should specify an additional way for the
                              code to determine the material structure. Currently supports 'qe', 'bgw', 'vasp', 'gpaw', 'deeph'.
        structure_path:       If structure_interface='qe': the folder containing data-file-schema.xml
                              If structure_interface='bgw': could be WFN, VSC, VKB
                              If structure_interface='vasp': the POSCAR file
                              If structure_interface='gpaw': the binary xxx.gpw file
                              If structrue_interface='deeph': the folder containing lat.dat, site_positions.dat, element.dat, info.json
        
        gw_root:        Folder containing sigma_hp.log.
        eqp_option:     'eqp0' or 'eqp1'.

        kgrid:          use None to read k-grid and k-weights from input data (qe-xml or bgw binary header); 
                        or specify a grid (e.g. [3, 3, 1]) to overwrite the original k-grid.
        '''
        
        self.start_time = time.time()
        
        if is_master():
            print()
            print('==============================================================================')
            print('Program HPRO')
            print('Author: Xiaoxun Gong (xiaoxun.gong@gmail.com)')
            print('==============================================================================')
            print()
            
        if lcao_interface is not None:
            lcao_interface = lcao_interface.lower()
        
        # determine structure, and check corresopnding input
        structure = None
        def check_structure(structure, stru1):
            if structure is None:
                structure = stru1
            elif structure != stru1:
                raise ValueError('Structure mismatch')
            return structure
        if hrdata_interface is not None and not overlaps_only:
            if hrdata_interface == 'qe-bgw':
                assert vscdir is not None
                stru1 = Structure.from_bgw(vscdir)
            elif hrdata_interface == 'qe-deephr':
                assert vscdir is not None
                stru1 = None # later we read xml file to determine structure
            else:
                raise NotImplementedError(f'Unknown hrdata_interface {hrdata_interface}')
            structure = check_structure(structure, stru1)
        if structure_interface is not None:
            assert structure_path is not None
            stru1 = load_structure(structure_path, structure_interface)
            structure = check_structure(structure, stru1)
        
        assert structure is not None, 'Must provide structure information'
        if is_master():
            structure.echo_info()
            print()
            
        # get lcaodata
        if lcao_interface is not None:
            assert structure is not None, 'Must provide structure information for lcao data to be initialized'
            lcaodata = LCAOData(structure, basis_path_root=lcaodata_root, aocode=lcao_interface)
            lcaodata.check_rstart()
        else:
            raise NotImplementedError()

        if is_master():
            print('Atomic orbital basis:')
            lcaodata.echo_info()
            print()
        
        # get wfndata
        assert wfn_interface is None
        wfndata = None
        assert hgdata_interface is None
        hgdata = None
        assert not overlaps_only
        
        # get hrdata
        vlocr_resource = None
        if hrdata_interface is not None:
            if not overlaps_only:
                if (hrdata_interface == 'qe-bgw') or (hrdata_interface == 'qe-deephr'):
                    assert vscdir is not None and upfdir is not None
                    vlocr, vlocr_resource = read_vloc_shared(vscdir, hrdata_interface.split('-')[1])
                    if is_master():
                        funch, funcg, projR = read_hrr(structure, upfdir, interface='qe')
                    else:
                        funch, funcg, projR = None, None, None
                else:
                    raise NotImplementedError(f'Unknown hrdata interface {hrdata_interface}')
            hrdata = (vlocr, funch, funcg, projR)
            if is_master():
                if vlocr is not None:
                    print('Real space grid dimensions: (' + ' '.join(f'{vlocr.shape[i]:5d}' for i in range(3)) + ')\n')
                print('Pseudopotential projectors:')
                projR.echo_info()
                print()
        else:
            hrdata = None

        self.structure = structure
        self.lcaodata = lcaodata
        self.wfndata = wfndata
        self.hgdata = hgdata
        self.ecutwfn = ecutwfn
        self.hrdata = hrdata
        self.vlocr_resource = vlocr_resource
        self.overlaps_only = overlaps_only

    
    @mpi_watch
    @simple_timer('\nJob done, total wall time = {t}\n')
    def run_pw2ao_rs(self, savedir, cutoffs=None):
        '''
        Convert plane-wave Hamiltonian to atomic orbital basis by integration in real space.
        The expensive local potential grid integral is distributed by AO pair blocks among ranks.
        The two-center interals for overlap / position / kinetic / non-local projector are root-only.

        Parameters:
        ---------
        savedir:    place where result will be saved.
        cutoffs:    Dict[str -> float], cutoff radius for each atomic species, in bohr. 
                    If not provided, the code will decide which hoppings are nonzero by considering 
                    the cutoff of the pseudopotential region and the cutoff of atomic orbitals.
        '''
        rank = 0 if comm is None else comm.rank
        nranks = 1 if comm is None else comm.size
        if is_master():
            if self.overlaps_only:
                print('\n============================')
                print('Calculating overlap matrices')
                print('============================\n')
            else:
                print('\n===============================================')
                print('Reconstructing PW Hamiltonian to AOs in real space')
                print('===============================================\n')

        assert self.ecutwfn is not None, 'Must provide cutoff energy ecutwfn'
        assert self.hrdata is not None
        vlocr, funch, funcg, projR = self.hrdata

        if is_master():
            save_structure_deeph(self.structure, savedir)

        ecut = self.ecutwfn
        basis = self.lcaodata
        stru = self.structure
        pairs_cut = None

        # ------------------------------------------------------------------
        # Root-only overlap matrix + position matrix
        # ------------------------------------------------------------------

        pairs_meta = None
        if is_master():
            basis.calc_phiQ(ecut * 1.1)
            # orbpairs1 saves pairs of AO basis and AO basis
            orbpairs1 = {}
            for spc1 in stru.atomic_species:
                for spc2 in stru.atomic_species:
                    pairs_this = []
                    for jorb in range(basis.norb_spc[spc2]):
                        r2 = basis.phirgrids_spc[spc2][jorb].rcut
                        for iorb in range(basis.norb_spc[spc1]):
                            r1 = basis.phirgrids_spc[spc1][iorb].rcut
                            pairs_this.append(OrbPair(
                                basis.phiQlist_spc[spc1][iorb],
                                basis.phiQlist_spc[spc2][jorb],
                                r1 + r2, 1
                            ))
                    orbpairs1[(spc1, spc2)] = pairs_this
            print('Calculating overlap matrix')
            overlaps = calc_overlap(basis, orbpairs1, Ecut=ecut)
            del orbpairs1

            # broadcast only light-weighted metadata from root rank to workers
            pairs_ij = overlaps.get_pairs_ij()
            pairs_meta = (
                pairs_ij.translations.copy(),
                pairs_ij.atom_pairs.copy(),
            )

            if cutoffs is not None:
                pairs_cut = pwc(self.structure, cutoffs)
                overlaps_cut = MatLCAO.setc(
                    pairs_cut, basis, filling_value=0., dtype='f8'
                )
                overlaps_cut.convert_to(overlaps)
                overlaps = overlaps_cut

            print('\nWriting overlap matrix to disk')
            save_mat_deeph(savedir, overlaps, filename='overlaps.h5', energy_unit=False)

            if not self.overlaps_only:
                # r * phi_i uses the same reciprocal bra channels for each ket orbital
                # precompute them only once for each radial AO shell
                pos_bras = {}
                for spc in stru.atomic_species:
                    pos_bras[spc] = []
                    for iorb in range(basis.norb_spc[spc]):
                        pos_bras[spc].append(prepare_position_bra(
                            basis.phirgrids_spc[spc][iorb], 
                            basis.phiQlist_spc[spc][iorb].rgd
                        ))

                # orbpairs2 saves position integral pairs of AO basis and AO basis
                orbpairs2 = {}
                for spc1 in stru.atomic_species:
                    for spc2 in stru.atomic_species:
                        pairs_this = []
                        for jorb in range(basis.norb_spc[spc2]):
                            r2 = basis.phirgrids_spc[spc2][jorb].rcut
                            for iorb in range(basis.norb_spc[spc1]):
                                r1 = basis.phirgrids_spc[spc1][iorb].rcut
                                pairs_this.append(PosOrbPair(
                                    basis.phirgrids_spc[spc1][iorb],
                                    basis.phiQlist_spc[spc2][jorb],
                                    r1 + r2,
                                    bras=pos_bras[spc1][iorb]
                                ))
                        orbpairs2[(spc1, spc2)] = pairs_this
                
                positions = calc_position(basis, orbpairs2, overlaps)
                print('\nWriting position matrix to disk')
                save_pos_deeph(savedir, positions, filename='positions.h5')
                del positions, orbpairs2, pos_bras

            del overlaps
            if cutoffs is not None:
                del overlaps_cut
            del pairs_ij
        
        if comm is not None:
            comm.Barrier()
        if self.overlaps_only:
            return

        if comm is not None:
            pairs_meta = comm.bcast(pairs_meta, root=0)
        assert pairs_meta is not None
        pairs_ij = PairsInfo(
            self.structure,
            np.asarray(pairs_meta[0], dtype=np.int64),
            np.asarray(pairs_meta[1], dtype=np.int64),
        )
        del pairs_meta
        pairs_global_idx = pairs_ij.get_indices().copy()

        # ------------------------------------------------------------------
        # Distributed Hloc: allocate each rank its own pair blocks.
        # ------------------------------------------------------------------

        # create temporary directory for each rank
        if is_master():
            print(f'\nConstructing Hamiltonian with {pairs_ij.npairs} blocks on {nranks} MPI rank(s)')
            tmpdir = os.path.join(savedir, '.ham_tmp')
            if os.path.isdir(tmpdir):
                shutil.rmtree(tmpdir)
            os.makedirs(tmpdir, exist_ok=True)
        if comm is not None:
            comm.Barrier()

        # balance block-memory among ranks accoording to norb_i*norb_j scale
        # equal pair counts can still produce imbalanced ranks with multi species
        block_bytes = np.empty(pairs_ij.npairs, dtype=np.int64)
        for ipair in range(pairs_ij.npairs):
            ia, ja = pairs_ij.atom_pairs[ipair]
            spc1 = self.structure.atomic_numbers[ia]
            spc2 = self.structure.atomic_numbers[ja]
            norb1 = basis.orbslices_spc[spc1][-1]
            norb2 = basis.orbslices_spc[spc2][-1]
            block_bytes[ipair] = 7 * norb1 * norb2 * np.dtype('f8').itemsize

        owners = np.empty(pairs_ij.npairs, dtype=np.int32)
        rank_loads = np.zeros(nranks, dtype=np.int64)
        for ipair in np.argsort(-block_bytes, kind='stable'):
            owner = int(np.argmin(rank_loads))
            owners[ipair] = owner
            rank_loads[owner] += block_bytes[ipair]
        own_pairs = np.flatnonzero(owners == rank)

        if is_master():
            mib = rank_loads / 1024.0**2
            print(
                '\nEstimated distributed Hamiltonian storage per rank: '
                f'min = {mib.min():.1f} MiB, max = {mib.max():.1f} MiB'
            )

        pairs_local = PairsInfo(
            self.structure,
            pairs_ij.translations[own_pairs].copy(),
            pairs_ij.atom_pairs[own_pairs].copy(),
        )
        del own_pairs, owners, rank_loads, block_bytes, pairs_ij

        FFTgrid = np.array(vlocr.shape)
        assert np.isrealobj(vlocr), 'Complex array not implemented'
        rprimFFT = self.structure.rprim / FFTgrid[:, None]
        dvol = self.structure.cell_volume / np.prod(FFTgrid)

        # cache real-space grids only for atoms touched by this rank
        # grids_site stores the non-zero grid point indices for each orbital
        grids_site = {}
        if pairs_local.npairs:
            atoms_local = np.unique(pairs_local.atom_pairs.reshape(-1))
            for ia in atoms_local:
                ia = int(ia)
                spc = self.structure.atomic_numbers[ia]
                poscart = self.structure.atomic_positions_cart[ia]
                grids_site_orb = []
                for iorb in range(basis.norb_spc[spc]):
                    rcut = basis.phirgrids_spc[spc][iorb].rcut
                    grids_site_orb.append(GridPoints.find(rprimFFT, rcut, poscart))
                grids_site[ia] = grids_site_orb

        Hloc_local = MatLCAO.setc_phiVdphi(
            pairs_local, basis, filling_value=0., dtype='f8'
        )
        del pairs_local
        construct_Hloc(self, vlocr, basis, FFTgrid, rprimFFT, dvol, grids_site, Hloc_local)
        del grids_site
        save_Hloc_shard(savedir, Hloc_local, pairs_global_idx, rank)
        del Hloc_local
        del pairs_global_idx
        if comm is not None:
            comm.Barrier()

        if is_master():
            print('\nMerging distributed Hloc and writing phiVdphi matrix')
            merge_Hloc_shard(savedir, nranks)
        if comm is not None:
            comm.Barrier()

        # Release the node-shared Vloc window collectively
        self.hrdata = (None, funch, funcg, projR)
        del vlocr
        if self.vlocr_resource is not None:
            window, node_comm = self.vlocr_resource
            node_comm.Barrier()
            window.Free()
            node_comm.Free()
            self.vlocr_resource = None
        if comm is not None:
            comm.Barrier()

        # ------------------------------------------------------------------
        # Root-only two-center kinetics and non-local Hkb,
        # And streaming the final assembly
        # ------------------------------------------------------------------

        if is_master():
            assert funcg is None
            
            # orbpairs3 saves pairs of AO basis and AO basis, for kinetics
            orbpairs3 = {}
            for spc1 in stru.atomic_species:
                for spc2 in stru.atomic_species:
                    pairs_this = []
                    for jorb in range(basis.norb_spc[spc2]):
                        r2 = basis.phirgrids_spc[spc2][jorb].rcut
                        for iorb in range(basis.norb_spc[spc1]):
                            r1 = basis.phirgrids_spc[spc1][iorb].rcut
                            pairs_this.append(OrbPair(
                                basis.phiQlist_spc[spc1][iorb],
                                basis.phiQlist_spc[spc2][jorb],
                                r1 + r2, 2
                            ))
                    orbpairs3[(spc1, spc2)] = pairs_this
            
            Hkin = calc_overlap(basis, orbpairs3, Ecut=ecut)
            del orbpairs3
            print('\nWriting kinetic matrix to disk')
            save_mat_deeph(savedir, Hkin, filename='kinetics.h5', energy_unit=True)
            del Hkin

            # orbpairs4 saves pairs of KB projectors and AO basis, for non-local Hkb
            projR.calc_phiQ(ecut * 1.1)
            orbpairs4 = {}
            for spc1 in stru.atomic_species:
                for spc2 in stru.atomic_species:
                    pairs_this = []
                    for jorb in range(basis.norb_spc[spc2]):
                        r2 = basis.phirgrids_spc[spc2][jorb].rcut
                        for iorb in range(projR.norb_spc[spc1]):
                            r1 = projR.phirgrids_spc[spc1][iorb].rcut
                            pair = OrbPair(
                                projR.phiQlist_spc[spc1][iorb],
                                basis.phiQlist_spc[spc2][jorb],
                                r1 + r2, 1
                            )
                            pair.grad_setup()
                            pairs_this.append(pair)
                    orbpairs4[(spc1, spc2)] = pairs_this

            olp_proj_ao = calc_overlap(projR, orbpairs4, basis, Ecut=ecut)
            del orbpairs4

            # release reciprocal grids of basis and projectors after two-center integrals
            basis.phiQlist_spc = None
            basis.phiQEcut = None
            projR.phiQlist_spc = None
            projR.phiQEcut = None
        
            # mats stores the non-local potential of each atom pair,
            # accumulating the contributions of all KB projectors 
            trans, atoms, mats, grad1, grad2 = get_mats_kb(olp_proj_ao, funch)
            proj_structure = olp_proj_ao.structure
            proj_lcaodata2 = olp_proj_ao.lcaodata2
            del olp_proj_ao

            Hkb = MatLCAO(
                proj_structure, trans, atoms, mats, proj_lcaodata2,
                mats_phiVdphi=grad2, mats_dphiVphi=grad1
            )
            del trans, atoms, mats, grad1, grad2
            Hkb.exchange_phiVdphi()
            Hkb.duplicate()

            print('\nWriting phiVkbdphi matrix to disk')
            save_phiVdphi_deeph(savedir, Hkb, filename='phiVkbdphi.h5', energy_unit=True)
            Hkb.clear_phiVdphi()
            print('\nWriting Hkb matrix to disk')
            save_mat_deeph(savedir, Hkb, filename='Hkb.h5', energy_unit=True)
            del Hkb

            print('\nStreaming final Hamiltonian to disk')
            assemble_ham(
                savedir, basis,
                final_pairs=pairs_cut if cutoffs is not None else None,
                filename='hamiltonians.h5'
            )
            if pairs_cut is not None:
                del pairs_cut

        if comm is not None:
            comm.Barrier()
